//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raven
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SID_DBEntities : DbContext
    {
        public SID_DBEntities()
            : base("name=SID_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sidLikertResponses153> sidLikertResponses153 { get; set; }
        public DbSet<sidOrgLevel> sidOrgLevels { get; set; }
        public DbSet<sidSurveydata> sidSurveydatas { get; set; }
        public DbSet<sidCasesView> sidCasesViews { get; set; }
        public DbSet<sidCommentsView> sidCommentsViews { get; set; }
        public DbSet<sidExplicit> sidExplicits { get; set; }
        public DbSet<sidImplicit> sidImplicits { get; set; }
    }
}
