//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raven
{
    using System;
    using System.Collections.Generic;
    
    public partial class sidCommentsView
    {
        public int frKey { get; set; }
        public int sdKey { get; set; }
        public System.DateTime sdDate { get; set; }
        public int ibkey { get; set; }
        public string surveyItem { get; set; }
        public string comment { get; set; }
        public bool frExpose { get; set; }
        public bool frEmphasize { get; set; }
        public Nullable<System.DateTime> frReviewDate { get; set; }
        public Nullable<int> frReviewer { get; set; }
        public bool frWarningEmailSent { get; set; }
    }
}
