//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raven
{
    using System;
    using System.Collections.Generic;
    
    public partial class sidCasesView
    {
        public int csKey { get; set; }
        public Nullable<int> adKey { get; set; }
        public int suKey { get; set; }
        public int tsKey { get; set; }
        public int orgKey { get; set; }
        public int adReqLoc { get; set; }
        public string orgAbbrev { get; set; }
        public string csGroupDescr { get; set; }
        public string suName { get; set; }
        public int csSurveyID { get; set; }
        public string csCase { get; set; }
        public Nullable<System.DateTime> adProcDate { get; set; }
        public Nullable<int> adProcessor { get; set; }
        public Nullable<System.DateTime> csDebriefDate { get; set; }
        public Nullable<int> csDebriefor { get; set; }
    }
}
