//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raven
{
    using System;
    using System.Collections.Generic;
    
    public partial class sidExplicit
    {
        public int edKey { get; set; }
        public int sdKey { get; set; }
        public int suKey { get; set; }
        public string siConstraint { get; set; }
        public int ibKey { get; set; }
        public int dbKey { get; set; }
        public string dbValue { get; set; }
        public string dbText { get; set; }
        public string dbCode { get; set; }
        public int dbSeq { get; set; }
        public int explicitNum { get; set; }
    }
}
