//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raven
{
    using System;
    using System.Collections.Generic;
    
    public partial class sidImplicit
    {
        public int idKey { get; set; }
        public int csKey { get; set; }
        public Nullable<int> suKey { get; set; }
        public int dbKey { get; set; }
        public string dbValue { get; set; }
        public Nullable<int> implicitNum { get; set; }
    }
}
