//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raven
{
    using System;
    using System.Collections.Generic;
    
    public partial class sidLikertResponses153
    {
        public int lrKey { get; set; }
        public int lrSdKey { get; set; }
        public Nullable<int> lrItemnr { get; set; }
        public int lrIbKey { get; set; }
        public decimal lrValue { get; set; }
    }
}
