//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raven
{
    using System;
    using System.Collections.Generic;
    
    public partial class sidOrgLevel
    {
        public int tsKey { get; set; }
        public int orgKey { get; set; }
        public string orgName { get; set; }
        public int orgLevel { get; set; }
        public Nullable<int> l12Key { get; set; }
        public string l12Name { get; set; }
        public Nullable<int> l11Key { get; set; }
        public string l11Name { get; set; }
        public Nullable<int> l10Key { get; set; }
        public string l10Name { get; set; }
        public Nullable<int> l9Key { get; set; }
        public string l9Name { get; set; }
        public Nullable<int> l8Key { get; set; }
        public string l8Name { get; set; }
        public Nullable<int> l7Key { get; set; }
        public string l7Name { get; set; }
        public Nullable<int> l6Key { get; set; }
        public string l6Name { get; set; }
        public Nullable<int> l5Key { get; set; }
        public string l5Name { get; set; }
        public Nullable<int> l4Key { get; set; }
        public string l4Name { get; set; }
        public Nullable<int> l3Key { get; set; }
        public string l3Name { get; set; }
        public Nullable<int> l2Key { get; set; }
        public string l2Name { get; set; }
    }
}
