//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raven
{
    using System;
    using System.Collections.Generic;
    
    public partial class sidSurveydata
    {
        public int sdKey { get; set; }
        public int sdID { get; set; }
        public int csKey { get; set; }
        public int sdLogin { get; set; }
        public int sdsuKey { get; set; }
        public string sdIP { get; set; }
        public string sdBrowser { get; set; }
        public int sdElapsed { get; set; }
        public System.DateTime sdDate { get; set; }
        public bool sdSubmitBtn { get; set; }
        public Nullable<int> le1 { get; set; }
        public Nullable<int> le2 { get; set; }
        public Nullable<int> le3 { get; set; }
        public Nullable<int> le4 { get; set; }
        public Nullable<int> le5 { get; set; }
        public Nullable<int> le6 { get; set; }
    }
}
